---
# file: tasks/main.yml

- include: package.yml
  tags:
    - hosts
    - package
- include: ssh.yml
  tags:
    - hosts
    - ssh
- include: bash.yml
  tags:
    - hosts
    - bash
- include: root.yml
  tags:
    - hosts
    - root
