---
# file: tasks/main.yml

- include: vars.yml
  tags:
    - vars
- include: package.yml
  tags:
    - package
- include: ssh.yml
  tags:
    - ssh
- include: bash.yml
  tags:
    - bash
- include: user.yml
  tags:
    - user
