---
# file: tasks/user.yml

- name: user - create directory ~/.rc.d
  file: path=~/.rc.d/ state={{hosts_auto|default(false)|ternary('directory', 'absent')}} mode="0700"

- name: user - activate automatic stuffs
  with_items: "{{hosts_auto_stuffs|default([])}}"
  file: path="~/.rc.d/{{item.name}}" state={{item.state|default('present')}} mode="0600"
  when: hosts_auto|default(false)

- name: user - update file .screenrc
  lineinfile: dest=~/.screenrc create=yes line='hardstatus alwayslastline "%{= kw}[%{G}%H%{-}] \# %?%-Lw%?[%{G}%n%f %t%{-}]%?%+Lw%?%?%=%-17< [%{B}%l%{-}]"'
