---
# file: tasks/user.yml

- name: user - register auto screen state
  set_fact:
    hosts_auto_state: "{{hosts_auto_screen|ternary('directory', 'absent')}}"

- name: user - create directory .ssh/auto
  file: path=~/.ssh/auto state={{hosts_auto_state}} mode="0700"

- name: user - update file .screenrc
  lineinfile: dest=~/.screenrc create=yes line='hardstatus alwayslastline "%{= kw}[%{G}%H%{-}] \# %?%-Lw%?[%{G}%n%f %t%{-}]%?%+Lw%?%?%=%-17< [%{B}%l%{-}]"'
